name: Clone 
on: [push]
jobs:
  get-repo:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    steps:

    - name: Get current repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.SECRETTOKEN }}
        path: ${{ github.workspace }}/trello2markdown
        ref: 'master'

