name: Clone 
on: [push]
jobs:
  get-repo:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    steps:

    - name: Get current repository
      uses: actions/checkout@v2
      with:
        path: ${{ github.workspace }}/trello2markdown
        ref: 'master'
    - name : Backup Trello stuff
      run: |
        mkdir ${{ github.workspace }}/trello_backup
        python3 ${{ github.workspace }}/trello2markdown/trello2markdown.py ${{ github.workspace }}/trello_backup  ${{ secrets.KEY }} ${{ secrets.TOKEN }}
      

